#cloud-config

fqdn: ${vm_hostname}

# Add groups to the system
groups:
  - ansible

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: ansible
    gecos: ansible
    shell: /bin/bash
    primary_group: ansible
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ${ansible_ssh_public_key}

# install packages
packages:
  - ansible
  - git

# provide the CNI deployment file.
#  https://cloudinit.readthedocs.io/en/latest/reference/modules.html#write-files
write_files:
  - path: /home/ansible/cni_weavenet_deamonset.yaml
    content: !!binary |
      ${cni_weave_installation_file_base64}
    permissions: '0640'
#    owner: ansible
  - path: /home/ansible/test_playbook.yaml
    content: !!binary |
      ${ansible_playbook_file_base64}
    permissions: '0640'
#    owner: ansible
  - path: /home/ansible/calico-custom-resources.yaml
    content: !!binary |
      ${cni_calico_custom_resources_file_base64}
    permissions: '0640'


    

# 
runcmd:
  - date > /home/ansible/DONE.txt
  - cd /home/ansible; git clone -b libvirt https://github.com/henkoch/k8s_auto_deployment.git
  - chown -R ansible:ansible /home/ansible
  - ansible-playbook  --extra-vars "kubernetes_version=v1.28" --extra-vars "cni_selection=calico" --extra-vars "node_type=${node_type}" --extra-vars "discovery_token=${discovery_token}" --extra-vars "discovery_token_ca_cert_hash=${discovery_token_ca_cert_hash}" test_playbook.yaml
#  - cd k8s_auto_deployment/ansible_playbook && ansible-playbook  --extra-vars "kubernetes_version=v1.28" ${node_type}.yaml
  - cp /var/log/cloud-init-output.log /home/ansible
  - id >> DONE.txt
  - echo "0.1.1" >> DONE.txt
  - date >> DONE.txt
